import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { FULL_HONEYCOMB_BOARD } from "../packages/game-engine/src/board.ts";

const outputPath = resolve("docs/provisional-board-transcription.md");
const source = "references/monsters-menace-america/components/board/full-game-setup.jpg";
const independentSource = "https://blugee.com/cdn/shop/files/Monsters-Menace-America-Board-Game-2_898x600.jpg?v=1711114433";
const thirdSource = "https://i.ebayimg.com/00/s/MTYwMFgxNjAw/z/rtYAAOSw9fVmDcjE/%24_3.JPG";
const closeupSource = "https://boardgamegeek.com/image/201674/monsters-menace-america";

const lines = [
  "# Provisional full-board transcription",
  "",
  "This is a working transcription ledger for cross-referencing board photographs. It is not authoritative game data and must not be imported by the engine or used to promote the MVP board.",
  "",
  "The ledger intentionally gives every one of the 254 coordinate-shell cells a review record. `hypothesis-land-or-feature` and `hypothesis-sea-or-coast` are deliberately coarse guesses based on the visible colour field, not authoritative terrain. `covered-or-unreadable` is for cells obscured by a playing piece, stomp marker, card, glare, perspective, or insufficient resolution. A later reference may replace any provisional state.",
  "",
  `- Primary reference: [full game setup photograph](../${source})` ,
  "- Cross-check reference: [full board top-down photograph](../references/monsters-menace-america/components/board/full-board-top-down.jpg)",
  `- Independent cross-check: [separate photographed game-board setup](${independentSource})`,
  `- Third cross-check: [another photographed board setup](${thirdSource})`,
  `- Close-up cross-check: [BoardGameGeek close-up board photograph](${closeupSource})`,
  "- Coordinate shell: `FULL_HONEYCOMB_BOARD`, 13 staggered rows, 254 cells",
  "- Promotion rule: no provisional guess in this file changes `packages/game-engine/src/board.ts` or clears production validation.",
  "",
  "## Candidate hypotheses to test against another reference",
  "",
  "These are board-level hypotheses only, not cell assignments: the visible outer blue regions are sea/coast; the green interior is land; grey city panels carry printed city names and bonus values; bright yellow/orange panels are Infamy sites; star symbols are military bases; purple/pink panels are Mutation sites; Hollywood and Los Angeles are visible in the southwest. Each hypothesis requires a cell-level cross-check before promotion.",
  "",
  "## Category correction from the four supplied photos",
  "",
  "The supplied photos provide a stronger visual classification than the earlier broad pass. Treat the grey skyline panels as cities, not the yellow/orange panels. The yellow/orange panels repeatedly carry `INFAMY` and are Infamy sites. The repeated star symbols are military bases. The grey city panels visibly use bonus labels such as `1hp`, `2d`, and `3d`; those are the panels to inspect when assigning city bonuses. Purple/pink `MUTATE` panels are Mutation sites. This correction supersedes the earlier hypothesis that some yellow/orange panels might be bases.",
  "",
  "## New straight-on full-board reference",
  "",
  "The newly supplied straight-on photograph is substantially better for tile matching than the earlier angled/cropped images. It shows the complete board frame, the full staggered hex field, the Great Lakes, both coasts, the grey city panels, Infamy panels, Mutation panels, and most coloured base stars in one view. Use it as the primary alignment reference for the next coordinate pass. The lower legend, pieces, and a small number of bottom-edge cells still obscure some artwork, so exact assignments remain provisional until the shell overlay is checked against this image.",
  "",
  "## Provisional city-candidate pass",
  "",
  "This pass marks likely city text or major-city regions for the next aligned review. These are hypotheses, not production labels or benefits.",
  "",
  "| Candidate | Provisional bonus | Basis | Confidence | Current action |",
  "| --- | --- | --- | --- | --- |",
  "| Winnipeg | +1 Health (tentative visual read) | City panel is readable in the close-up photograph and appears to show `1hp`. | medium for bonus; low for shell coordinate | Keep as an unmapped city candidate until the close-up is aligned to the full shell. |",
  "| Minneapolis | Roll 1 die (tentative visual read) | City panel is readable in the close-up photograph and appears to show a one-die marker. | medium-low for bonus; low for shell coordinate | Cross-check against a straight-on reference before promotion. |",
  "| Omaha | Roll 1 die (tentative visual read) | City panel appears to show a one-die marker in the close-up photograph. | medium-low for bonus; low for shell coordinate | Cross-check against the third setup image before assigning. |",
  "| Kansas City | +1 Health (inferred) | Central-plains city panel appears readable or strongly suggested; smaller printed city treatment is assumed provisionally. | low-medium for bonus; low for shell coordinate | Treat as a candidate only; correct when the physical board is available. |",
  "| Seattle | +1 Health (inferred from development marker and city scale) | Existing development fixture uses `1HP`; physical-board mapping remains unverified. | low | Use only as a provisional search hypothesis. |",
  "| San Francisco | Roll 2 dice (inferred from development marker and major-city scale) | Existing development fixture uses `2D`; physical-board mapping remains unverified. | low | Use only as a provisional search hypothesis. |",
  "| Los Angeles | Roll 3 dice (inferred from development marker and major-city scale) | Existing development fixture uses `3D`; Hollywood/L.A. area is visibly present, but exact city cell remains unverified. | low-medium for region; low for bonus/cell | Keep Hollywood and Los Angeles as separate candidate spaces. |",
  "| Chicago | +2 Health (inferred from development marker and major-city scale) | Existing development fixture uses `2HP`; physical-board mapping remains unverified. | low | Use only as a provisional search hypothesis. |",
  "| New York | Roll at least 2 dice (corrected provisional inference) | Major-city scale makes the earlier 1-die guess too low; the physical-board value remains unread. | medium-low for bonus; low for shell coordinate | Keep as a corrected hypothesis until the printed New York panel is confirmed. |",
  "| Philadelphia | Roll 2 dice (provisional inference) | Visible/evident east-coast city candidate adjacent to New York; major-city scale suggests it should not be a 1-die city. | low-medium for bonus; low for shell coordinate | Add as a separate city candidate beside New York; confirm against the physical panel. |",
  "| Miami | No city bonus assigned; Challenge-site candidate | Existing development fixture classifies Miami as Challenge rather than city. | low for physical board | Keep separate from the city-bonus list until the printed space is verified. |",
  "| Denver | No city bonus assigned; military-base candidate | Existing development fixture classifies Denver as a base rather than city. | low for physical board | Keep separate from the city-bonus list until the printed space is verified. |",
  "| Dallas | No city bonus assigned; Mutation-site candidate | Existing development fixture classifies Dallas as a Mutation site rather than city. | low for physical board | Keep separate from the city-bonus list until the printed space is verified. |",
  "| Boston, Washington, Houston, Atlanta, New Orleans, Toronto, Salt Lake City, Phoenix | Unassigned | Plausible major-city search targets based on map geography, not yet read from the references. | low | Inspect only; do not invent a bonus until a city panel is visible. |",
  "",
  "All bonuses above are provisional hypotheses. The game rules support fixed Health gains and one-, two-, or three-die city rolls, but these candidate values are not source-approved. The close-up proves that non-empty city panels exist in the central/northern board area, but perspective and cropping prevent a reliable conversion to `row / column` or axial keys. The next useful artifact is an aligned crop or a straight-on board photograph with the shell overlay visible.",
  "",
  "## Bonus-first city inference",
  "",
  "For this pass, the exact printed city name is secondary. A blurry skyline panel can still be recorded as a city candidate if its surrounding geography is recognisable and its bonus prefix is visible or reasonably inferable.",
  "",
  "| Approximate region / orientation | Example city labels used only for orientation | Provisional bonus pattern | Confidence |",
  "| --- | --- | --- | --- |",
  "| Southeast interior | Atlanta / Nashville | Atlanta: roll 2 dice; Nashville: roll 1 die. | low-medium; bonus-first, names/cells provisional |",
  "| Northeast corridor | New York / Philadelphia / Boston | New York: at least 2 dice; Philadelphia: 2 dice; Boston: 1–2 dice pending panel read. | low-medium |",
  "| Great Lakes | Chicago / Detroit / Cleveland / Toronto | Larger skyline panels: 2–3 dice; smaller neighbouring panels: 1 die or +2 Health. | low |",
  "| Central plains | Minneapolis / Omaha / Kansas City | Minneapolis: 1 die; Omaha: 1 die; Kansas City: +1 Health. | medium-low |",
  "| Pacific and southwest | Seattle / San Francisco / Los Angeles | Seattle: +1 Health; San Francisco: 2 dice; Los Angeles: 3 dice. | low-medium |",
  "| Gulf and southern coast | Houston / New Orleans / Miami | Use 1 Health or 1 die for smaller-looking panels; reserve 2 dice for the clearly larger skyline panels. | low |",
  "",
  "These are deliberately approximate bonus assignments, not claims that every named city has been located. When a later photo shows the grey panel's printed prefix, keep the bonus even if the guessed city name changes. Do not use the bright yellow/orange Infamy panels or star bases as city-bonus evidence.",
  "",
  "## Provisional military-base star matching",
  "",
  "The four supplied photos are sufficient to classify the visible coloured star symbols using the original branch-piece colour key. This is a provisional tile pass: the photos show overlapping/cropped regions, so the entries below use visual regions rather than pretending to have exact axial keys.",
  "",
  "| Visible star branch | Provisional tile/region matches | Confidence |",
  "| --- | --- | --- |",
  "| Air Force | Yellow stars across the upper-central board, central interior, lower-central board, and eastern/southeastern coast. | medium for branch; low for exact shell key |",
  "| Marines | Red stars clustered along the eastern seaboard and additional red-star coastal/southern candidates. | medium for branch; low for exact shell key |",
  "| Navy | Blue star/base candidates around the Great Lakes, lower Mississippi/Gulf area, and coastal water-adjacent tiles. | medium for branch; low for exact shell key |",
  "| Army | Green/olive star candidates in inland central and eastern interior tiles. | low-medium for branch; low for exact shell key |",
  "| National Guard | Orange star candidates where the star is orange rather than yellow; none is yet clear enough in the supplied crops for an exact tile assignment. | low for branch; low for exact shell key |",
  "",
  "Do not confuse these stars with the bright yellow/orange `INFAMY` panels or with the grey skyline city panels. The branch classification is useful for the next aligned overlay, but no base branch or star position is promoted into `FULL_HONEYCOMB_BOARD` yet.",
  "",
  "## Straight-on photo: unobscured base candidates",
  "",
  "The new straight-on photograph makes the following unobscured star positions usable as provisional base candidates. Row/column values are approximate image-grid positions: row 0 is the top board row and column 0 is the leftmost position in that row. Stomp-covered or piece-covered stars are intentionally omitted.",
  "",
  "| Approx. row / column | Provisional branch | Evidence | Confidence |",
  "| --- | --- | --- | --- |",
  "| 0 / 2 | Navy | Blue star near the northwest/Pacific edge. | medium |",
  "| 1 / 9 | Air Force | Yellow star in the upper-central interior. | medium |",
  "| 6 / 12 | Air Force | Yellow star in the central-eastern interior. | medium |",
  "| 9 / 11 | Air Force | Yellow star in the lower-central interior. | medium |",
  "| 10 / 15 | Air Force | Yellow star near the Gulf/southeastern coast. | medium-low |",
  "| 6 / 18 | Marines | Red star on the eastern coastal band. | medium |",
  "| 7 / 17 | Marines | Red star on the eastern coastal band. | medium |",
  "| 8 / 17 | Marines | Red star farther south on the eastern coastal band. | medium |",
  "| 7 / 14 | Army | Green/olive star-like base in the eastern interior. | low-medium |",
  "| 9 / 15 | Army | Green/olive star-like base in the lower eastern interior. | low-medium |",
  "| 10 / 10 | Navy | Blue star/base near the Gulf/coastal transition. | low-medium |",
  "| 11 / 13 | Navy | Blue star/base near the lower coastal water. | low-medium |",
  "| — | National Guard | No unobscured orange star is clear enough in this photograph to add safely. | unresolved |",
  "",
  "These positions are a provisional inventory for visual validation, not yet canonical `HexKey` assignments. The next pass should overlay the shell coordinates on the supplied straight-on photograph and either confirm or move each candidate by one cell where needed.",
  "",
  "## Independent image comparison",
  "",
  "The independent setup image confirms the board family, filled honeycomb extent, blue sea/coast boundary, green land field, Hollywood area, city panels, site markers, bases, and the general distribution of printed spaces. It does not resolve exact shell-cell assignments because its perspective, component placement, and lower-resolution presentation obscure or shift many cells. It therefore raises confidence in broad visual classifications but leaves feature coordinates and benefits provisional.",
  "",
  "The third setup image is especially useful for the central, eastern, and southern board areas because it shows more printed map surface under a different arrangement of pieces and cards. It independently supports the broad land/sea silhouette and the presence of the same feature families. It still does not provide a geometrically aligned, unobscured cell-by-cell source, so terrain confidence can increase while feature confidence remains low.",
  "",
  "The close-up BoardGameGeek photograph materially improves feature-level evidence: it shows readable printed city names and health-style values, repeated Infamy panels, Mutation markers, military-base artwork, Challenge-style star markers, and the placement relationship between printed spaces and military units. This raises confidence in the feature vocabulary and visible text patterns, but not in the axial-coordinate mapping because the photograph is a perspective crop without the full shell visible.",
  "",
  "## Ocean line and coastal-water note",
  "",
  "The photographed board shows an irregular ocean boundary rather than a rectangular outer border. Record the ocean line as three connected coastal regions: the Pacific coast along the western edge, the Gulf coast wrapping the south-west/southern edge, and the Atlantic coast along the eastern edge. The visible blue cells immediately offshore are ocean/sea candidates; the land cells touching them are coastal cells and must not be collapsed into ordinary land. Great Lakes and other inland blue areas must be recorded separately as lake candidates, not as ocean.",
  "",
  "For the next aligned transcription pass, trace the coastline cell by cell and then author the corresponding boundary edges. The current shell's edge-column `hypothesis-sea-or-coast` labels are only a review prompt: they do not represent the physical ocean line and must not be promoted as the final coastline.",
  "",
  "## Obscured-cell assessment",
  "",
  "The primary setup photograph is obscured most heavily across the southwest and south-central board by cards, reference sheets, dice, stomp markers, and playing pieces. The independent image exposes more of that underlying surface and uses a different piece layout, so it helps distinguish permanent printed artwork from temporary components. However, it still leaves some of the same lower-board cells covered and introduces perspective shift; it is not safe to transfer a visible marker to a shell coordinate by eye alone.",
  "",
  "Result of the cross-check: no previously obscured cell has enough independent evidence to promote an exact label, city Health category, site type, base branch, lair, water class, or barrier. Those cells remain provisional in the ledger. Broad sea/coast versus land hypotheses are retained where both images agree; feature candidates remain `—` until a close, aligned reference or human physical-board review resolves them.",
  "",
  "## Cell ledger",
  "",
  "| Hex key | Row / column | Provisional visual state | Feature candidate | Terrain confidence | Feature confidence | Reference note |",
  "| --- | --- | --- | --- | --- | --- |",
  ...Object.values(FULL_HONEYCOMB_BOARD.hexes)
    .sort((a, b) => a.coord.r - b.coord.r || a.coord.q - b.coord.q)
    .map((hex) => {
      const row = hex.coord.r;
      const column = hex.coord.q + Math.floor(row / 2);
      const edgeCandidate = row === 0 || row === 12 || column === 0 || column === (row % 2 === 0 ? 19 : 18);
      const visualState = edgeCandidate ? "hypothesis-sea-or-coast" : "hypothesis-land-or-feature";
      return `| \`${hex.key}\` | ${row} / ${column} | ${visualState} | — | medium (broad visual field) | low for exact coordinate; medium for visible feature vocabulary | Compare all five references; exact feature placement remains unverified. |`;
    }),
  "",
  "## Cross-reference workflow",
  "",
  "1. Add a second reference image and record its path in the relevant row's reference note.",
  "2. Replace a hypothesis with `observed-land`, `observed-sea`, `observed-lake`, `observed-feature`, or `covered-or-unreadable` only when the image supports that distinction.",
  "3. Record a guessed feature as `hypothesis:<type>` rather than silently treating it as observed.",
  "4. Promote a cell only after its label, water class, features, source reference, and reciprocal edges have been reviewed.",
  "",
];

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${lines.join("\n")}\n`);
console.log(`Generated ${outputPath}`);
